services:
  test:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RUNTIME_TYPE: test

  execute:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RUNTIME_TYPE: execute-single
      DAY: ${DAY}
      PROBLEM: ${PROBLEM}