services:
  test-problems:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RUNTIME_TYPE: test

  execute-problems:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RUNTIME_TYPE: execute