[project]
name = "aoc25"
version = "0.1.0"
description = "Collection of solutions for Advent of Code challenges 2025"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pytest>=9.0.1",
    "ruff>=0.14.7",
    "typer>=0.20.0",
]
